GET  http://localhost:3000/api/test/all

###

POST  http://localhost:3000/api/auth/signup

{
    "username": "igataku",
    "email": "mail",
    "password": "00000000",
    "createdAt": "2000-09-10",
    "updatedAt": "2020-11-23",
    "roleId": 1
}